server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 175.24.5****
    username: ***
    password: l***
    virtual-host: /leyou

leyou:
  sms:
    accessKeyId: *********** # 你自己的accessKeyId
    accessKeySecret: ************ # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: S*********** # 模板名称
