server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 175.24.50.240.
    username: 11111
    password: 1111
    virtual-host: /leyou

leyou:
  sms:
    accessKeyId: *********************** # 你自己的accessKeyId
    accessKeySecret: *********** # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: ****************************** # 模板名称
