server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 
    username: 
    password: 
    virtual-host: 

leyou:
  sms:
    accessKeyId: # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate:  # 模板名称
