server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/**   #搜索微服务
    user-service: /user/**  #用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/**
    order-service: /order/**
  retryable: true
  add-host-header: true
  sensitive-headers:
ribbon:
  ConnectTimeout: 500 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 2 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
leyou:
  jwt:
    pubKeyPath: D:\\tools\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
      allowPaths:
        - /api/auth
        - /api/search
        - /api/user/register
        - /api/user/check
        - /api/user/code
        - /api/item
        - /api/cart